### ISSUE TITLE
Does this library support mqtt v5?

### ISSUE THREAD

**Issue by Zapnologica** [eclipse/paho.mqtt.embedded-c#232] opened 2021-12-09 11:12 UTC
We are looking to use the ResponseTopic feature outlined in v5.0 MQTT protocol>

Does this library support it, and if not are there plans to support it and when?

**Comment by scaprile** [comment] 2021-12-09 11:51
Possible duplicate of issue #102

**Comment by KonssnoK** [comment] 2022-05-12 06:44
the answer is no.
Looking partially at implementation there is no support for properties in the publish serializer nor the AUTH packet.

**Comment by lmapii** [comment] 2022-05-20 13:32
I just see that the last commit is from 5 years ago, is this project still active?

**Comment by CIPop** [comment] 2023-07-18 23:34
ResponseTopic should work as expected for code in the `develop` branch. I have added samples that use properties: https://github.com/eclipse/paho.mqtt.embedded-c/blob/develop/MQTTPacket/samples/v5pub0sub1.c#L221

> is this project still active?

Yes, it is! I am actively working together with @icraggs on wrapping up MQTTv5 support that was already available for MQTTPacket in the `develop` branch. I am a developer with Microsoft Azure IoT and my work is sponsored by our group.
Next on my list is to create a `MQTTClientv5-c` equivalent.

**Comment by icraggs** [comment] 2023-11-29 12:35
I'm going to close this, as we are working on a release with MQTT 5 support.

**Closed by icraggs** 2023-11-29 12:35 UTC
Labels: question

**Comment by Singa17** [comment] 2024-05-08 04:38
> ResponseTopic should work as expected for code in the `develop` branch. I have added samples that use properties: https://github.com/eclipse/paho.mqtt.embedded-c/blob/develop/MQTTPacket/samples/v5pub0sub1.c#L221
> 
> > is this project still active?
> 
> Yes, it is! I am actively working together with @icraggs on wrapping up MQTTv5 support that was already available for MQTTPacket in the `develop` branch. I am a developer with Microsoft Azure IoT and my work is sponsored by our group. Next on my list is to create a `MQTTClientv5-c` equivalent.

[CIPop](https://github.com/CIPop)
Hi CIPop, Any update on the MQTTClientv5-c?
