### ISSUE TITLE
Move includes to a subdirectory

### ISSUE THREAD

**Issue by Equidamoid** [eclipse/paho.mqtt.embedded-c#236] opened 2022-06-27 13:02 UTC
Hello, 

The current code requies includes like `#include <MQTTClient.h>`, which can lead to a mess if you happen to have multiple mqtt-related dependencies.

How about prefixing the includes with something like `paho/` or `paho-embedded/`?

I'm willing to prepare a PR for this if the maintainers agree (and if this repo isn't as abandoned as it looks).

**Comment by CIPop** [comment] 2023-07-18 23:17
I found that most embedded projects do not have folder-separated include files (e.g. STMicro's BSP, ARM's CMSIS all expect single-level includes and a properly defined `INCLUDE` path).
That said, because the name is generic (i.e. does not include "Paho"), I see how name collisions could appear. 

My preference is towards `paho-embedded/` or similar to disambiguate from the paho.mqtt.c's "MQTTClient.h". We could also change the name of the client to include "Paho" or "PahoEmbedded" although I find that a bigger breaking change.

**Comment by CIPop** [comment] 2023-07-19 21:19
Similar / duplicate to #156.

**Comment by icraggs** [comment] 2023-11-29 15:37
Close as duplicate of #156

**Closed by icraggs** 2023-11-29 15:37 UTC
Labels: duplicate
